=== ale-ben/Teal-Owl/ManifestUploader/docs/manifestSchema schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "Teal-Owl_Backend/product.schema.json/v1.0",
	"title": "Teal-Owl_manifest",
	"description": "A manifest generated by Teal-Owl published and consumed by Teal-Owl reader",
	"type": "object",
	"properties": {
		"version": {
			"description": "The version of the manifest",
			"type": "string"
		},
		"author": {
			"description": "The author of the manifest",
			"type": "string"
		},
		"document": {
			"description": "The document the manifest is for",
			"type": "string"
		},
		"timestamp": {
			"description": "The timestamp of the manifest",
			"type": "string",
			"format": "date-time"
		},
		"hashList": {
			"description": "The list of hashes of each paragraph of the document",
			"type": "array",
			"items": {
				"type": "string"
			},
			"minItems": 1
		},
		"notes": {
			"description": "The notes the author added before pubblication",
			"type": "string"
		}
	},
	"required": [
		"version",
		"author",
		"document",
		"timestamp",
		"hashList"
	]
}

=== ale-ben/Teal-Owl/docs/drive-download-20231206T103101Z-001/TestDocument_manifest.json
{"version":"1.0","author":"alessandro.benetton@studio.unibo.it","document":"1JUhzMh3RAOVqns21JaIAWl-hD3Isz869YmbGb15pAH8","hashList":["7ea35a73c3b4d7616696eb7d5bd416fd63430d62a4de2f9c004e050ae289b257","21a4444e568f53c4ab20aaa6f541b3d40f48f70a70eb6601b757544148f7a504","af9d8adb7a69ccc758c1eb30e59bef7bcbb7e894f3452c2eeb5e34078ed0f479"],"timestamp":"2023-12-06T10:16:58.464Z"}

=== ale-ben/Teal-Owl/apps/reader/docs/TestDocument_watermarked/TestDocument_manifest.json
{
	"version": "1.0",
	"author": "alessandro.benetton@studio.unibo.it",
	"document": "1JUhzMh3RAOVqns21JaIAWl-hD3Isz869YmbGb15pAH8",
	"hashList": [
		"316a8a13bc03f99edf8de0e024a7a69e3ddfcee8f8eb8745b0a809ddd58f9928",
		"af9d8adb7a69ccc758c1eb30e59bef7bcbb7e894f3452c2eeb5e34078ed0f479"
	],
	"timestamp": "2023-12-12T15:52:22.835Z"
}
